export const GLOBALVAR_BIOBANK_URL = process.env.REACT_APP_BIOBANK_URL;
export const GLOBALVAR_APP_VERSION = process.env.REACT_APP_VERSION;
export const GLOBALVAR_NOTIFICATIONS_REFRESH_MINS = process.env.REACT_APP_NOTIF_REFRESH_INMINS;